### PR TITLE
Scrypt 1.2.1

### PR DESCRIPTION
**Pull request by jpouellet**
All the patches we were using locally made it into this release, so we can drop them now.

Notes on how I verified the new 2017 signing key are in the first commit (but of course don't just take my word for it). Links to the patches in upstream are in the 2nd commit.

`qubes-builder/keyrings/linux-scrypt/scrypt-trustedkeys.gpg` also needs to be updated to add the tarsnap 2017 key, but I didn't investigate what source code change that requires, I just added it there manually on my machine for now.

### CODE REVIEW

**Comment by jpouellet** [comment]
Oh... and check failed because I have a new qubes signing key too. Will upload to keyservers as soon as I have ensured sufficient availability of my revocation cert for it and have cross-signed with my old qubes signing key.

**Comment by jpouellet** [comment]
The reason I got sidetracked and updated this was precisely because I wanted to use scrypt to safely store my revocation cert... bit of a chicken-and-egg problem :)

**Comment by jpouellet** [comment]
Okay, key should be good now. Is the only way to re-run the CI to push a dummy commit?

**Comment by marmarek** [comment]
> Okay, key should be good now. Is the only way to re-run the CI to push a dummy commit?

In theory yes. In practice travis have "restart build" in the we UI, and I can rerun signature checking manually. You know, you can propose something better: https://github.com/marmarek/signature-checker/ (triggering not only on push, but also on a comment like "recheck"?).

**Comment by marmarek** [comment]
Travis fails on this for a reason: key importing is wrong, since you've renamed key files.

**Comment by jpouellet** [comment]
Do you happen to know off hand where else it needs to be changed?

It builds fine for me ([log here](https://gist.githubusercontent.com/anonymous/28542291aa4d3ad2f9899f4da9939eb1/raw/5cb7f2aaa6d84ce99377a78bf9d3a9ae5293165b/-)), and a grep for the old filename turns up nothing.

If not, I'll look into how qubes-builder/keyrings/ is populated...

**Comment by marmarek** [comment]
> Do you happen to know off hand where else it needs to be changed?

Yes, `$(wildcard *-key.asc)` in `Makefile.common`.

**Comment by jpouellet** [comment]
Thanks. A get-sources-extra & build after `rm -rf qubes-builder/keyrings/linux-scrypt` succeeds now.

**Comment by jpouellet** [comment]
Not sure why the code-signing check failed again:
```
$ check-git-signature --pull-request 1 --clone https://github.com/QubesOS/qubes-linux-scrypt --print-keyid
4747332C27533622
$ echo $?
0
```

**Comment by jpouellet** [comment]
...and now it's passed... ¯\\\_(ツ)\_/¯

**Pull request merged**
